etriebe/dnd-randomizer

module.json
scripts/compendium.js
scripts/creaturetypechooser.js
scripts/environmentchooser.js
scripts/playerchooser.js
scripts/utils/DialogUtils.js
styles/encounterGenerator.css
templates/compendium.hbs
templates/creaturetype.hbs
templates/environment.hbs
templates/player.hbs

Fixing issue from parent repo.
https://github.com/theripper93/dnd-randomizer/issues/48

Add check all/uncheck all/invert buttons

---

scripts/creatureCodex.js
scripts/utils/ActorUtils.js
scripts/utils/FoundryUtils.js
styles/encounterGenerator.css

Add item list to the table and add item description and creature biography to table as hidden so the content is searchable.

Add creature item and bio data to table and fix some style issues

---

scripts/dnd5e/EncounterUtils5e.js

Move to more reliable access methods for this code.

Use better supported methods for getting actor object and actor id

---

scripts/compendium.js
scripts/dnd5e/NPCActor5e.js
scripts/localmodule.js

This will only index the selected compendiums when that button is selected. 
Fixing #13
Fixing #15

Only index selected compendiums

---

scripts/spawner.js
scripts/utils/ActorUtils.js

Abstract getTokenDocument call and import SFLOCALCONSTS

Fix v9 errors

---

scripts/dnd5e/EncounterUtils5e.js
scripts/encounter.js
scripts/propagator.js
scripts/spawner.js
scripts/utils/FoundryUtils.js
styles/encounterGenerator.css

1. Fix random encounter generation
2. Fix template spawning
3. Fix broken item links
4. Prevent overriding css for actor links
Fix the following issues #22 #21 #19

Fix a bunch of random errors in Stochastic Fantastic

---

scripts/localconst.js

Fix pf2e constants for encounter generation

---

scripts/pf2e/EncounterUtilsPf2e.js
scripts/pf2e/NPCActorPf2e.js
scripts/utils/FoundryUtils.js

Fix pf2e actor links. Will need a reindex of compendiums

---

scripts/dialog.js

Add pf2e utils reference

---

scripts/compendium.js
scripts/config.js
scripts/dialog.js
scripts/dnd5e/EncounterUtils5e.js
scripts/localconst.js
scripts/localmodule.js
scripts/pf2e/EncounterUtilsPf2e.js
scripts/treasurechooser.js
scripts/utils/GeneralUtils.js
scripts/utils/ModuleUtils.js
templates/dialog.hbs
templates/treasure.hbs
templates/usePCsDialog.hbs

Get PF2E loot generation and filtering working

---

scripts/encounter.js
scripts/localconst.js
scripts/pf2e/EncounterUtilsPf2e.js
scripts/spawner.js
scripts/utils/FoundryUtils.js

Ensure PF2E loot actors work well

---

README.md
scripts/config.js
scripts/dialog.js
scripts/module.js

Rip out of donjon code since endpoint is no longer running

---

scripts/localmodule.js

Make all getDocument requests at once and await them all to let that code be optimized as best it can by Javascript.

Add a speed boost for possibly speeding up Forge indexing

---

scripts/creaturetypechooser.js
scripts/environmentchooser.js
scripts/localmodule.js
scripts/utils/ActorUtils.js
scripts/utils/FoundryUtils.js
templates/creaturetype.hbs
templates/environment.hbs

1. Fix #43 
2. A couple QOL fixes to fix text for some features that either no longer exist or were confusing

Add a lot of optimizations for remote servers/ForgeVTT

---

styles/encounterGenerator.css
templates/dialog.hbs

Fix style issues for toolbar

---

scripts/localmodule.js

Fixes https://github.com/etriebe/dnd-randomizer/issues/46

Add absolute URL support to loadFile

---

module.json
scripts/compendium.js
scripts/config.js
scripts/creatureCodex.js
scripts/creaturetypechooser.js
scripts/dialog.js
scripts/dnd5e/EncounterUtils5e.js
scripts/dnd5e/NPCActor5e.js
scripts/dnd5e/PCActor5e.js
scripts/encounter.js
scripts/environmentchooser.js
scripts/localconst.js
scripts/localmodule.js
scripts/pf2e/EncounterUtilsPf2e.js
scripts/pf2e/NPCActorPf2e.js
scripts/pf2e/PCActorPf2e.js
scripts/playerchooser.js
scripts/treasurechooser.js
scripts/utils/ActorUtils.js
scripts/utils/FoundryUtils.js
styles/encounterGenerator.css
templates/compendium.hbs
templates/usePCsDialog.hbs

1. Add base foundry v11 support
2. Remove dependency on local index and use compendium.getIndex instead
3. Some UI clean-up

Foundry v11 support

---

README.md
module.json
scripts/combatestimatedialog.js
scripts/config.js
scripts/creatureCodex.js
scripts/dialog.js
scripts/dnd5e/EncounterUtils5e.js
scripts/dnd5e/NPCActor5e.js
scripts/dnd5e/PCActor5e.js
scripts/encounter.js
scripts/localmodule.js
scripts/module.js
scripts/pf2e/EncounterUtilsPf2e.js
scripts/treasurechooser.js
scripts/utils/ActorUtils.js
scripts/utils/FoundryUtils.js
scripts/utils/GeneralUtils.js
styles/combatEstimate.css
templates/CombatEstimateDialog.hbs

1. Add Combat Estimate to SF module
2. Make Combat Estimate triggerable from SF encounters dialog
3. Fix a lot of bugs

Add combat estimate functionality to Stochastic Fantastic

---

scripts/dialog.js
scripts/dnd5e/EncounterUtils5e.js
scripts/encounter.js
scripts/pf2e/EncounterUtilsPf2e.js
styles/encounterGenerator.css
templates/dialog.hbs
templates/usePCsDialog.hbs

And add a CR button to the actor link

Add option to limit an encounter to a single creature type

---

scripts/localmodule.js

This is to help the previous release.

Update to load images from system path and replace in the index if it's available

---

scripts/utils/ActorUtils.js

Make biography not have some null checks

---

scripts/localconst.js
scripts/localmodule.js
scripts/utils/ActorUtils.js
scripts/utils/GeneralUtils.js

Get creaturetype working for pf2e now that it is an array of values

---

scripts/utils/GeneralUtils.js

Fix one issue for user where creaturetype is null/undefined.

Add an extra null check to getUniqueValuesFromListOfArrays

---

scripts/dialog.js
scripts/utils/EncounterUtils.js

Fix #78 which added PF2e specific code to be used for everyone, which breaks things.

Remove pf2e specific references from main code

---

scripts/utils/ActorUtils.js
scripts/utils/EncounterUtils.js

Fix dnd5e for encounter generation

---

scripts/dialog.js

Prevent deleted actors from favorited encounters from causing the dialog to fail to load
